<html>
<head>
<title>TestNG:  Default test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Default test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>5/5/0</td>
</tr><tr>
<td>Started on:</td><td>Fri May 30 12:19:26 IST 2014</td>
</tr>
<tr><td>Total time:</td><td>5 seconds (5263 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode()'><b>demoCaseAgeCode</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-23376028" onClick='toggleBox("Output-23376028", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-23376028" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-23376028">
SELECT distinct age_code FROM aers_demo<br/>
Expected : [YR, MON, WK, DY, HR, DEC, MIN, SEC, '']<br/>
Actual : [YR,  , MON, WK, DY, HR, DEC, M, F, 64, SEC, MIN, 85]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [9] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:345)
	... 24 more
</pre></div><a href='#' onClick='toggleBox("stack-trace23376028", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace23376028'><pre>java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [9] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:345)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup()'><b>demoCaseAgeGroup</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-32380043" onClick='toggleBox("Output-32380043", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-32380043" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-32380043">
SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00<br/>
Expected : [0]<br/>
Actual : [631]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = &apos;Not Available&apos; AND age != &apos;&apos; AND age_code != &apos;&apos; AND age not like (&apos;%-%&apos;) AND age not like (&apos;%.%&apos;) AND age != 0 AND age != 00
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 631 expected [0] but found [631]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:382)
	... 24 more
</pre></div><a href='#' onClick='toggleBox("stack-trace32380043", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace32380043'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = &apos;Not Available&apos; AND age != &apos;&apos; AND age_code != &apos;&apos; AND age not like (&apos;%-%&apos;) AND age not like (&apos;%.%&apos;) AND age != 0 AND age != 00
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 631 expected [0] but found [631]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:382)
	... 24 more
</pre></div></td>
<td>4</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode()'><b>demoCaseGenderCode</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-13782591" onClick='toggleBox("Output-13782591", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-13782591" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-13782591">
SELECT distinct gender_code FROM aers_demo<br/>
Expected : [F, M, UNK, NS, U, '']<br/>
Actual : [F,  , M, UNK, NS, null, YR, N, Y, U]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [6] but found [10]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:227)
	... 24 more
</pre></div><a href='#' onClick='toggleBox("stack-trace13782591", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace13782591'><pre>java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [6] but found [10]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:227)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC()'><b>demoCaseGenderDEC</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-20526817" onClick='toggleBox("Output-20526817", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-20526817" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-20526817">
SELECT distinct gender_dec FROM aers_demo<br/>
Expected : null<br/>
Actual : []<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct gender_dec FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:257)
	... 24 more
</pre></div><a href='#' onClick='toggleBox("stack-trace20526817", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace20526817'><pre>java.lang.AssertionError: SELECT distinct gender_dec FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:257)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseValidTo()'><b>demoCaseValidTo</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-13599389" onClick='toggleBox("Output-13599389", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-13599389" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-13599389">
SELECT count(*) FROM aers_demo where valid_to is null<br/>
Expected : [0]<br/>
Actual : [13]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 13 expected [0] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:76)
	... 24 more
</pre></div><a href='#' onClick='toggleBox("stack-trace13599389", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace13599389'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 13 expected [0] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:76)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCASE_ID()'><b>demoCASE_ID</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-16749745" onClick='toggleBox("Output-16749745", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-16749745" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-16749745">
SELECT count(*) FROM aers_demo where case_id is null<br/>
Expected : [0]<br/>
Actual : [0]<br/>
</div>
</td>
<td></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness()'><b>demoCaseSeriousness</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-1812813" onClick='toggleBox("Output-1812813", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1812813" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1812813">
SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)<br/>
Expected : [0]<br/>
Actual : [0]<br/>
</div>
</td>
<td></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom()'><b>demoCaseValidFrom</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-2955420" onClick='toggleBox("Output-2955420", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-2955420" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-2955420">
SELECT count(*) FROM aers_demo where valid_from is null<br/>
Expected : [0]<br/>
Actual : [0]<br/>
</div>
</td>
<td></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoFDA_date()'><b>demoFDA_date</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-32519825" onClick='toggleBox("Output-32519825", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-32519825" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-32519825">
SELECT count(*) FROM aers_demo where fda_date is null<br/>
Expected : [0]<br/>
Actual : [0]<br/>
</div>
</td>
<td></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoISR_ID()'><b>demoISR_ID</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-10481832" onClick='toggleBox("Output-10481832", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-10481832" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-10481832">
SELECT count(*) FROM aers_demo where isr_id is null<br/>
Expected : [0]<br/>
Actual : [0]<br/>
</div>
</td>
<td></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@290fbc</td></tr>
</table><p>
</body>
</html>